[project]
name = "torch-pc"
version = "0.1.0"
authors = [
    { name="Noah Schiro", email="noahschiro@rocketmail.com" },
]
description = "A torch-based predictive coding library"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
dependencies = [
    "torch>=2.0",
    "torchvision>=0.21.0",
    "tqdm>=4.67.3",
]

# This is the version of pytorch I need to work with my cuda card
[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch       = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
torchaudio  = { index = "pytorch-cu124" }

[tool.setuptools]
packages = ["torch_pc"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
